# Generated by Django 6.0.1 on 2026-01-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('mentor', 'mentor'), ('student', 'student')], default='student', max_length=20),
        ),
    ]
